use testingsystem;
CREATE VIEW vw_DSNV_Sale AS
SELECT * FROM `account` A
INNER JOIN DEPARTMENT D
ON A.Departmentid = D.Departmentid
WHERE A.Departmentid = N'sale';
SELECT *
FROM vw_DSNV_Sale;
-- cte
WITH CTE_DSNV_SALE AS(
	SELECT A.*, d.DEPARTMENT AS 'PB'
    FROM `ACCOUNT` A
    INNER JOIN DEPARTMENT D
    ON A.DEPARTMENTID = D.DEPARTMENTID
    WHERE D.DEPARTMENTNAME =N'SALE')
  SELECT * FROM   CTE_DSNV_SALE;
-- C2:
CREATE VIEW VW_THONGTINACCOUNT AS
WITH CTE_DSSOLUONGACCOUNT AS  (
	SELECT COUNT(GA1.ACCOUNTID) AS COUNTGA1
    FROM GROUPACCOUNT GA
    GROUP BY GA1.ACCOUNTID
)
SELECT A.ACCOUNTID, A.USERNAME, COUNT(GA.ACCOUNTID) AS SL
FROM GROUPACCOUNT GA
INNER JOIN `ACCOUNT` A
ON GA.ACCOUNTID = A.ACCOUNTID
GROUP BY GA.ACCOUNTID
HAVING COUNT(GA.ACCOUNTID)= SELECT MAX(COUNTGA1)AS MAXCOUNT CTE_DSSOLUONGACCOUNT);
SELECT * FROM VW_THONGTINACCOUNT


